name: "Bug Report"
description: "Report a bug to help us improve the project"
title: "[BUG] - <Short description>"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "## Bug Report\nPlease fill out the required fields below."

  - type: input
    id: summary
    validations:
      required: true
    attributes:
      label: "Summary"
      description: "Provide a short summary of the issue."
      placeholder: "E.g., The login button doesn't work on Chrome"

  - type: dropdown
    id: severity
    attributes:
      label: "Severity Level"
      description: "How critical is this bug?"
      options:
        - "Low (minor issue, doesn't block usage)"
        - "Medium (annoying but workaround available)"
        - "High (blocks key functionality)"
        - "Critical (app crashes or data loss)"
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: "Programming Language"
      description: "Which programming language is the project written in?"
      options:
        - "python"
    validations:
      required: true

  - type: input
    id: project_folder
    attributes:
      label: "Project Folder"
      description: "Locate the project folder where the bug is present."
      placeholder: "path/to/project"
      value: "."
    validations:
      required: true

  - type: input
    id: source_folder
    attributes:
      label: "Source Folder"
      description: "Locate the source folder where the bug is present (relative to the project folder)."
      placeholder: "src"
      value: "src"
    validations:
      required: true
  
  - type: input
    id: test_folder
    attributes:
      label: "Test Folder"
      description: "Locate the test folder (relative to the project folder)."
      placeholder: "tests"
      value: "tests"
    validations:
      required: true
  
  - type: input
    id: environment
    attributes:
      label: "System Information"
      description: "Provide system details (e.g., OS, browser, version)."
      placeholder: "Windows 11, Chrome v110, App v2.0.1"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "E.g., Clicking submit does nothing."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What should happen instead?"
      placeholder: "E.g., After clicking submit, the user should be logged in."
    validations:
      required: true

  - type: textarea
    id: logs_screenshots
    attributes:
      label: "Logs"
      description: "Attach any logs or screenshots that might help."
      placeholder: "Drag and drop images or paste logs here."
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: "Confirmation"
      options:
        - label: "I have searched for **existing** issues before submitting this."
          required: true
        - label: "I have tested with the **latest version** of the application."
