name: "Auto Bugfix"

on:
  workflow_dispatch:

jobs:
  bugfix:
    
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout Project Repository"
        uses: actions/checkout@v4
        # with:
        #   repository: "afri-bit/ai-coder"
        #   token: ${{ secrets.GH_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: List Files for Debugging
        run: ls -al

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      # - TODO: Parse the issue and generate the json file

      # TODO: Run the bug spray on the project repository based on the issue number

      # TODO: Generate hash for the brach name

      # TODO: Create a new branch and commit the changes

      # TODO: Push the changes to the project repository

      # TODO: Create a pull request
