name: "Auto Bugfix"

on:
  workflow_dispatch:

env: 
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  bugfix:
    
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout Project Repository"
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: List Files for Debugging
        run: ls -al

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Set up GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Fetch Issue Markdown
        run: |
          gh issue view 2 --repo ${{ github.repository }} --json body -q .body > issue.md

      - name: Show fetched Markdown
        run: cat issue.md

      # TODO: Add more element to the issue.md like adding header 1
          
      - name: Parse the markdown issue
        run: |
          debugsprai parse issue.md --output issue.json

      - name: Show parsed issue
        run: |
          cat issue.json

      - name: Run Bug Spray
        run: |
          debugsprai debug issue.json

          ls -al .airesults

      # TODO: Run the bug spray on the project repository based on the issue number

      # TODO: Create a new branch and commit the changes

      # TODO: Push the changes to the project repository

      # TODO: Create a pull request
